[package]
name = "rust-opc"
version = "0.1.0"
edition = "2021"

[dependencies]
opcua = { git = "https://github.com/locka99/opcua", version = "0.13.0" }
tokio = { version = "1.36.0", features = ["full"] }
